name = "songs-spotify-api"
main = "cloudflare-worker.js"
compatibility_date = "2023-10-30"

[vars]
ENVIRONMENT = "production"

# Secrets to set via: wrangler secret put SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_ID = "your-spotify-client-id"
# SPOTIFY_CLIENT_SECRET = "your-spotify-client-secret"
